#!/usr/bin/env python
import copy
import glob
import os.path
import sys

from pyPdf import PdfFileWriter, PdfFileReader



output = PdfFileWriter()
output_page_number = 0
alignment = 2           # to align on even pages



path = sys.argv[-1]
filepath = os.path.join(path, '*.pdf')



print filepath
files = glob.glob(os.path.join(path, '*.pdf'))
print files



for filename in sorted(files):
    # This code is executed for every file in turn
    print filename
    input = PdfFileReader(open(filename))
    for p in [input.getPage(i) for i in range(0,input.getNumPages())]:
        # This code is executed for every input page in turn
        output.addPage(p)
        output_page_number += 1

    for i in range(4):
        output.addBlankPage()
        output_page_number += 1
    
    while output_page_number % alignment != 0:
        output.addBlankPage()
        output_page_number += 1



filename = 'out.pdf'
with open(filename, 'wb') as outfile:
    output.write(outfile)

